spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diary?characterEncoding=UTF-8
    username: root
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: username2da
    password: ylxpssgawcnodtky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ture
          ssl:
            enable: true
            trust: smtp.gmail.com
#          protocols: TLSv1.2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
#              BasicBinder: TRACE
